### ISSUE TITLE
How Work ?

### ISSUE THREAD

**Issue by YasinRezvani** [Amir-Mohamad/AparatDownloader#1]
Can you explain more how it works, please?

**Comment by Amir-Mohamad** [comment]
Um, that repo was for a long time ago, I dont know what the code was and
how it works, but i think there were details on README that shows you how
to work with AparatDownloader repo.
Dont forget to leave a star on repo =)

**Comment by YasinRezvani** [comment]
ok, thank you @Amir-Mohamad
